[package]
name = "simulator"
version = "0.1.0"
authors = ["imger"]

[dependencies]
game_sdk = {path = "../game_sdk"}
logic_player = {path = "../logic_player"}
logger = {path = "../logger"}
threadpool = "1.7"
argparse = "0.2.2"
time = "0.1"
rand = "*"